apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rumkol9wi-python
  janus-idp.io/tekton: rumkol9wi-python
  backstage.io/kubernetes-id: rumkol9wi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rumkol9wi-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
