apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rumkol9wi-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rumkol9wi-python 
  name: rumkol9wi-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rumkol9wi-python 
